### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by amandeep-verma** [sriram-rajamani/python-njmvcappt#1]
Firstly thanks for writing this amazing code.
This isn't working for me on mac as winsound library is exclusively available for windows. So i took off the winsound.Beep part of the code and tried to run it with after installing all the libraries.
The program says "Something went wrong", each time I am running it. I added couple of tests to see where program is crashing and found on this line --->  soup = BeautifulSoup(page_html.text ,'lxml')
To which I added another try and catch to  line --->  soup = BeautifulSoup(page_html.text ,'lxml'), so program can check for each of location_arr and it fails each time.

I would highly appreciate if you can fix this.

**Comment by verotheelf** [comment]
I'm also a mac user. Replaced the winsound and everything seems to be working smoothly. Do you have the updated code posted somewhere?

**Comment by amandeep-verma** [comment]
https://github.com/amandeep-verma/python-njmvcappt/blob/main/dl-alert.py

Here it is. I was able to make the code run on my raspberry pi but on my mac it always goes to except condition. So just to check if it is the problem is with 1 location, I added another try and except block inside the "for" block to check but its failing at just one location or all.
It is failing at all location on my mac.

**Comment by verotheelf** [comment]
I'm having a hard time getting the code to break. Seems ok to me. Threw it in a venv and occasionally I could get it to fail, usually when I messed around with the interpreter, but even that wasn't consistent. 

Which version of python are you using?
How are you running the code? - Terminal, IDE, etc
Do you have a shebang? --> #!/usr/bin/env python3

**Comment by mayanksinha181** [comment]
Hello, 
I am facing the same issue as Amandeep. 
soup = BeautifulSoup(page_html.text ,'lxml') --> this is failing. 
I have windows 10 machine. 

Appreciate is anyone has any insights on how to fix

**Comment by sriram-rajamani** [comment]
Hi,
Apologize for the delay in response. I just checked and for some reason the request library is not working for me. I updated that with URLLIB.

find below the old code and the new code to get the html data.
Also note that the parameter for the bueatifulsoup, the page_html is without the .text attribute in the new one.
I tested it and it works perfectly for me.

Let me know in case of any issues


###OLD CODE###
import requests
page_html = requests.get(base_url_link+location)
soup = BeautifulSoup(page_html.text,'lxml')

### NEW CODE
import urllib.request
with urllib.request.urlopen(base_url_link+location) as response:
   page_html = response.read()
soup = BeautifulSoup(page_html ,'lxml')

**Comment by sriram-rajamani** [comment]
> I'm having a hard time getting the code to break. Seems ok to me. Threw it in a venv and occasionally I could get it to fail, usually when I messed around with the interpreter, but even that wasn't consistent.
> 
> Which version of python are you using?
> How are you running the code? - Terminal, IDE, etc
> Do you have a shebang? --> #!/usr/bin/env python3

I am using Anaconda Navigator 1.9.12 and opening the  cmd.exe within that and running in command prompt in Win10 laptop. I dont have shebang.

**Comment by mayanksinha181** [comment]
Thanks Sriram. 
Looks like the code works for new license url only. 
I am trying to find slots for out of state transfers but when I change the url to  https://telegov.njportal.com/njmvc/AppointmentWizard/7/ . ( '7' in the end is for out of state transfers ) , the code breaks. Any idea how to make the code work for out of state transfers ? 

Help would greatly appreciated, I have been trying to find a slot for a month now but no success. 

Thanks,

**Comment by sriram-rajamani** [comment]
> Thanks Sriram.
> Looks like the code works for new license url only.
> I am trying to find slots for out of state transfers but when I change the url to https://telegov.njportal.com/njmvc/AppointmentWizard/7/ . ( '7' in the end is for out of state transfers ) , the code breaks. Any idea how to make the code work for out of state transfers ?
> 
> Help would greatly appreciated, I have been trying to find a slot for a month now but no success.
> 
> Thanks,



I think the issue is, the location codes for the same location differ for each type of service.

for example, for Freehold location, 
for License renewal, the location code  is 113
https://telegov.njportal.com/njmvc/AppointmentWizard/11/113

and for Initial permit, it is 197
https://telegov.njportal.com/njmvc/AppointmentWizard/15/197

and for transfer it is 54
https://telegov.njportal.com/njmvc/AppointmentWizard/7/54


You need to change the location array with the respective ids for Transfers.
Visit the below home page and click on the locations in the map to find our the location IDs.
https://telegov.njportal.com/njmvc/AppointmentWizard/7

Hope this clarifies.

**Comment by sriram-rajamani** [comment]
Code updated in the main branch
